### ISSUE TITLE
Cant close notifications

### ISSUE THREAD

**Issue by jrogatis** [puranjayjain/react-materialui-notifications#125]
i cant close the notification ..
I try both the top right close button and a close function at a dismiss button trying set the open prop.

material-ui ver 0.17.1
react 15.4.1

showNotification(msgTitle, msgAdditionalText, msgOverflowText) {
    ReactMaterialUiNotifications.showNotification({
      title: msgTitle,
      additionalText: msgAdditionalText,
      icon: <Message />,
      iconBadgeColor: '006400',
      overflowText: msgOverflowText,
      timestamp: moment().format('h:mm A'),
    });
  }
 <ReactMaterialUiNotifications
          desktop
          transitionName={{
            leave: 'dummy',
            leaveActive: 'fadeOut',
            appear: 'dummy',
            appearActive: 'zoomInUp',
          }}
          transitionAppear
          transitionLeave
        />

**Comment by puranjayjain** [comment]
@jrogatis thanks for reporting it. It seems we already have a solution, the project needs to be migrated to react version newer, which is causing the problem.

**Comment by jrogatis** [comment]
can i help at any way ? I really like your component and if you need some help please let me know !

**Comment by puranjayjain** [comment]
I'm trying to solve it using key fix which someone pointed out in an earlier issue discussion. I'll try to fix it on my end, if not possible will definitely ask for your help via a Pull request.

**Comment by puranjayjain** [comment]
I made some changes and have pushed a commit can you do the following :-
1. download a copy of the latest commit
2. run npm install or yarn install
3. execute gulp run or use the gulp run.bat file
4. test the demo that opens up and tell me the results

**Comment by jrogatis** [comment]
demo works ! let me try using the component at my project now! Tks!

**Comment by jrogatis** [comment]
oh no... its not working at my project... no messages... just dons't close when i click the x... Anything that i can do help ?

**Comment by puranjayjain** [comment]
There must be something that you might be doing wrong in your implementation. If it is open source I can take a look at it.

**Comment by jrogatis** [comment]
its a no profit project for Free Code Camp 
this is the link for the branch
https://github.com/jrogatis/LetsMeet/tree/material-ui_implement
Really appreciate any help ! Your component will be a perfect match since we use material-ui !

**Comment by Meesam** [comment]
can't close notification.

**Comment by jrogatis** [comment]
I figure out what was causing the issue ... After you delete the notification at the notifications array you need to use a 
forceUpdate to re render the component... since you are not using the notifications array as a state controller.

**Comment by puranjayjain** [comment]
can you make a pull request to fix it? It would be a really helpful update

**Comment by jrogatis** [comment]
ok i will try today

**Comment by imlooke** [comment]
I can't close notification in my program, but I figure out the issue in my program that I don't add the animation class fadeOut and zoomInUp.And it worked!Hope useful.

**Comment by da-poodle** [comment]
Same case here as imlooke, notifications where not disapearing, then removed transitions and it worked fine.

**Comment by puranjayjain** [comment]
fixed in PR #129
