### ISSUE TITLE
still taking PropTypes from React

### ISSUE THREAD

**Issue by ido-ofir** [puranjayjain/react-materialui-notifications#131]
still taking PropTypes from React in 'master/src/app/ReactMaterialUiNotifications.js':
![image](https://user-images.githubusercontent.com/6238323/29067695-5155bf20-7c3c-11e7-8288-7f11f86a4335.png)
Thanks :)

**Comment by puranjayjain** [comment]
fixed :)

**Comment by ido-ofir** [comment]
Thanks!!
will you be publishing with this fix soon?

**Comment by puranjayjain** [comment]
Already done
