### ISSUE TITLE
Notifications doesn't removes from DOM

### ISSUE THREAD

**Issue by irrvrsl** [puranjayjain/react-materialui-notifications#98]
Hi! I've explored your project's demo site and saw, that currently notifications doesn't removes from DOM, when clicking on 'close' button. Is it desired behavior?

**Comment by puranjayjain** [comment]
It must be a bug introduced with the latest version of material ui. Are you using a local copy of the demo? Can you also tell me your browser and environment (desktop / mobile)

**Comment by irrvrsl** [comment]
Chrome 55,
react: 15.4.1
material-ui: 0.16.5,
desktop env.
I saw that on your https://puranjayjain.github.io/react-materialui-notifications/

**Comment by trelly** [comment]
it can't remove Notificaiton Dom when click the close button

**Comment by trelly** [comment]
![image](https://cloud.githubusercontent.com/assets/172466/21929524/e49c9704-d9cb-11e6-8ff9-4bbf127ae2e9.png)
lastest version material-ui for paper component did't support key prop.

**Comment by puranjayjain** [comment]
@trelly thank you for pointing out the reason shall fix this.

**Comment by puranjayjain** [comment]
this has been fixed in #116
